apiVersion: v1
kind: PersistentVolume
metadata:
  name: staticfiles-pv
  namespace: app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/staticfiles"
