apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: app
data:
  DJANGO_ENV: "production"
  DATABASE_ENGINE: "django.db.backends.postgrsesql"
  POSTGRES_HOST: "postgres.database.svc.cluster.local"
  POSTGRES_PORT: "5432"
  ALLOWED_HOSTS: "localhost"
