apiVersion: v1
kind: Secret
metadata:
  name: consenso-tls
  namespace: app
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBN3ZMWFVsTzFTMWo0aFFGSjdjNHoKK01qWFRKNnlFbnBHeloyZ0xibjZXbC9WTDZvRnBUOHp2Ni9kZkZkczgvVmZWNXo5ejF1Wm9aTU8xUHZYNURCTgorMkNsWVB2MFVWQlBsVG5EYlIzaXhxWGdHK09KWWY1Vmg2QjVxTWV6TndJREFRQUJBb0dBQ3ErZVpwOVRnK0YvCjllOCtxWUovVmhWKzVGbEIvdTNKa0tqdnZTMVpaNElXRzV2N2xCdHZaTk9KWjBYOUFjeHhvSzlFck5rMGU4UDUKenpFMmI1STVBSzVsVk1JVUV3SURBUUFCCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRHU4dGRTVTdWTFdQaUYKQVVuOXpqUDR5TmRNbnFJZWtiTm5hQXR1ZnBhWDlVdnFnV2xQek8vcjk5RVYyeno5VjlYblAzUFc1bWhrdzdVKwo5ZmtNRTM3WUtsZysvUlFVVStWWTUyeDNvWUtwZUFaNDRsaC9sV0hvSG1vejdOM0FnTUJBQUVDZ2dFS3ZxZWwKbW1uMU9ENWYvWHZQcW1DZjFZVmZ1UlpRZjdjbVFxTys5TFZsbWdqWWJtL3VVRzI5azA0bG5SZjBCekhHZ3IwUwpzMlRSN3cvblBNVFp2a2prQXJuVlV3Z2hRVEFFQUFRPT0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQ==
